// AUTO-GENERATED by generate_docs.py -- do not edit.
window.COMPLIANCE_STATUS = {
  "generated_at": "2026-07-01T08:47:48+00:00",
  "framework": "NIST SP 800-171 Rev 2",
  "scoring_model": "DoD Assessment Methodology (SPRS), base score 110",
  "summary": {
    "sprs_score": 105,
    "sprs_base": 110,
    "points_deducted": 5,
    "sprs_basis": "catalog covers 110 of 110 controls; unsatisfied controls deduct their DoD weight",
    "automated_coverage_pct": 17.1,
    "controls_total": 110,
    "controls_applicable": 82,
    "controls_with_evidence": 14,
    "automated_total": 14,
    "status_counts": {
      "met": 13,
      "attested": 46,
      "policy": 22,
      "na": 15,
      "inherited": 13,
      "partial": 1
    },
    "type_counts": {
      "automated": 14,
      "attested": 46,
      "policy": 22,
      "na": 15,
      "inherited": 13
    },
    "deductions": [
      {
        "control_id": "3.11.2",
        "status": "partial",
        "points": 5,
        "reason": "Vulnerability scanning (pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps)) runs on every push/PR, but not on a fixed schedule, so newly disclosed CVEs in unchanged dependencies are not caught until the next commit."
      }
    ]
  },
  "controls": [
    {
      "id": "3.1.1",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Limit system access to authorized users and processes.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "AC.L1-3.1.1",
        "hipaa": "164.312(a)(1)",
        "onc": "170.315(d)(1)",
        "part2": "2.16"
      },
      "status": "met",
      "finding": {
        "control_id": "3.1.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "All protected routes require authentication via the require_auth decorator; unauthenticated requests are rejected.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/auth_middleware.py:47",
            "detail": "require_auth() authenticates the session before the handler runs."
          }
        ],
        "objective_ids": [
          "3.1.1[e]"
        ],
        "collector": "access_control",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "c052f0e419b984d466166797991efc9b9c7009f692386f9ad654eb59b9078dea"
      }
    },
    {
      "id": "3.1.2",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Limit system access to permitted transactions and functions.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "AC.L1-3.1.2",
        "hipaa": "164.312(a)(1)",
        "onc": "170.315(d)(1)",
        "part2": "2.16"
      },
      "status": "met",
      "finding": {
        "control_id": "3.1.2",
        "status": "met",
        "method": "EXAMINE",
        "summary": "RBAC restricts each route to a required permission (has_permission), and patient visibility is further limited to a user's care teams (_apply_rbac).",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/auth_middleware.py:71",
            "detail": "require_auth(permission=...) enforces per-route permission."
          },
          {
            "kind": "source-file",
            "ref": "backend/routes/patients.py:148",
            "detail": "_apply_rbac() limits patient rows to the caller's care teams."
          }
        ],
        "objective_ids": [
          "3.1.2[b]"
        ],
        "collector": "access_control",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "e03f1d4c6bf4772c036383d4e24596ed4de2691f8226ba1ca4f900b1a8c0bb2a"
      }
    },
    {
      "id": "3.1.3",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Control the flow of CUI in accordance with approved authorizations.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.3",
        "hipaa": "164.312(e)(1)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.3",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Enforced by VPC subnet tiers and security-group chaining; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.4",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Separate duties of individuals to reduce risk of malevolent activity.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.1.4",
        "status": "policy",
        "method": "POLICY",
        "summary": "RBAC role design separates duties; attested via policy.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.5",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Employ least privilege, including for privileged accounts.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.5",
        "hipaa": "164.312(a)(1)",
        "onc": "170.315(d)(1)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.5",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Least-privilege RBAC + care-team scoping; attested, automation pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.6",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Use non-privileged accounts for nonsecurity functions.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.6",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Attested via policy.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.7",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Prevent non-privileged users from executing privileged functions; log.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.7",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Privileged actions gated by permission checks and audited.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.8",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Limit unsuccessful logon attempts.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.8",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.8",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Account lockout after 5 failed logons; automation pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.9",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Provide privacy and security notices consistent with CUI rules.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.9",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.1.9",
        "status": "policy",
        "method": "POLICY",
        "summary": "Login banner / policy; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.10",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Use session lock with pattern-hiding after inactivity.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.10",
        "hipaa": null,
        "onc": "170.315(d)(5)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.10",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "15-minute idle session timeout; automation pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.11",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Terminate a user session after a defined condition.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.11",
        "hipaa": null,
        "onc": "170.315(d)(5)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.11",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Server-side session revocation; automation pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.12",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Monitor and control remote access sessions.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.12",
        "hipaa": "164.312(e)(1)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.12",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "All access via CloudFront/ALB; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.13",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Employ cryptographic mechanisms to protect remote access.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.13",
        "hipaa": "164.312(e)(2)(ii)",
        "onc": "170.315(d)(9)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.13",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "TLS 1.2+ everywhere; overlaps 3.13.8 (automated).",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.14",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Route remote access via managed access control points.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.14",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.14",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "CloudFront -> ALB managed entry; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.15",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Authorize remote execution of privileged commands.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.15",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.1.15",
        "status": "policy",
        "method": "POLICY",
        "summary": "Policy-governed; ECS exec via SSM.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.16",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Authorize wireless access prior to allowing connections.",
      "sprs_weight": 5,
      "type": "na",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.16",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.1.16",
        "status": "na",
        "method": "N/A",
        "summary": "No wireless networks in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.17",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Protect wireless access using authentication and encryption.",
      "sprs_weight": 5,
      "type": "na",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.17",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.1.17",
        "status": "na",
        "method": "N/A",
        "summary": "No wireless networks in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.18",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Control connection of mobile devices.",
      "sprs_weight": 5,
      "type": "na",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.18",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.1.18",
        "status": "na",
        "method": "N/A",
        "summary": "No managed mobile devices in scope.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.19",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Encrypt CUI on mobile devices and mobile computing platforms.",
      "sprs_weight": 3,
      "type": "na",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.19",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.1.19",
        "status": "na",
        "method": "N/A",
        "summary": "No mobile devices in scope.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.20",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Verify and control connections to external systems.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AC.L1-3.1.20",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.1.20",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Boundary managed by CloudFront/WAF; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.21",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Limit use of portable storage devices on external systems.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "AC.L2-3.1.21",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.1.21",
        "status": "na",
        "method": "N/A",
        "summary": "No portable storage in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.1.22",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Control CUI posted or processed on publicly accessible systems.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AC.L1-3.1.22",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.1.22",
        "status": "policy",
        "method": "POLICY",
        "summary": "No CUI on public systems; attested via policy.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.2.1",
      "family": "AT",
      "family_name": "Awareness and Training",
      "title": "Ensure managers and users are aware of security risks.",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AT.L2-3.2.1",
        "hipaa": "164.308(a)(5)(i)",
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.2.1",
        "status": "policy",
        "method": "POLICY",
        "summary": "Security awareness training program; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.2.2",
      "family": "AT",
      "family_name": "Awareness and Training",
      "title": "Ensure personnel are trained to carry out security duties.",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AT.L2-3.2.2",
        "hipaa": "164.308(a)(5)(i)",
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.2.2",
        "status": "policy",
        "method": "POLICY",
        "summary": "Role-based training; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.2.3",
      "family": "AT",
      "family_name": "Awareness and Training",
      "title": "Provide security awareness training on insider threat.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AT.L2-3.2.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.2.3",
        "status": "policy",
        "method": "POLICY",
        "summary": "Insider-threat awareness; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.3.1",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Create and retain system audit logs.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.1",
        "hipaa": "164.312(b)",
        "onc": "170.315(d)(10)",
        "part2": "2.16"
      },
      "status": "met",
      "finding": {
        "control_id": "3.3.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Audit records are generated by log_access() and persisted to the AuditLog table (retained in Postgres).",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:29",
            "detail": "log_access() creates and stores an AuditLog row per event."
          }
        ],
        "objective_ids": [
          "3.3.1[e]",
          "3.3.1[f]"
        ],
        "collector": "audit_chain",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "f44ccc756422e990d90db7754db655b5445a7229fbabc0130fe7245abfff8311"
      }
    },
    {
      "id": "3.3.2",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Ensure actions are uniquely traceable to users.",
      "sprs_weight": 3,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.2",
        "hipaa": "164.312(b)",
        "onc": "170.315(d)(2)",
        "part2": "2.16"
      },
      "status": "met",
      "finding": {
        "control_id": "3.3.2",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Every audit record carries user_id, uniquely tracing actions to the acting user.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:9",
            "detail": "user_id is part of the audit record content and hash input."
          }
        ],
        "objective_ids": [
          "3.3.2[a]",
          "3.3.2[b]"
        ],
        "collector": "audit_chain",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "3041c5b18177bd668cd72539c862fcb13209630f70b6805d298e96d5da3c832f"
      }
    },
    {
      "id": "3.3.3",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Review and update logged events.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.3.3",
        "status": "policy",
        "method": "POLICY",
        "summary": "Logged-event set reviewed periodically; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.3.4",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Alert on audit logging process failure.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.3.4",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "CloudWatch alarms; automation pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.3.5",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Correlate audit review, analysis, and reporting.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.3.5",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Audit query/filter API; correlation collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.3.6",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Provide audit record reduction and report generation.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.6",
        "hipaa": null,
        "onc": "170.315(d)(3)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.3.6",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Audit log API supports filtering/report; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.3.7",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Provide authoritative time source for timestamps.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.3.7",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "UTC timestamps from host NTP; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.3.8",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Protect audit information from modification and deletion.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.8",
        "hipaa": "164.312(b), 164.312(c)(1)",
        "onc": "170.315(d)(2)",
        "part2": "2.16"
      },
      "status": "met",
      "finding": {
        "control_id": "3.3.8",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Audit log is tamper-evident: a per-tenant SHA-256 hash chain makes any modification or deletion of a past record mathematically detectable via /api/audit/verify.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:9",
            "detail": "_compute_hash() = SHA-256(content || prev_hash) builds the chain."
          },
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:9",
            "detail": "Each entry references the previous entry's hash (per-tenant chain)."
          },
          {
            "kind": "source-file",
            "ref": "backend/routes/audit.py:246",
            "detail": "GET /api/audit/verify walks the chain and reports tampering."
          }
        ],
        "objective_ids": [
          "3.3.8[b]",
          "3.3.8[c]"
        ],
        "collector": "audit_chain",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "7e1ab282570bf134086265d971dbaf722f5bb6d65617ca09be6f92bee8c7b473"
      }
    },
    {
      "id": "3.3.9",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Limit audit log management to a privileged subset of users.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "AU.L2-3.3.9",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.3.9",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "audit.view permission restricts access; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.1",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Establish and maintain baseline configurations.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.1",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.4.1",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Terraform IaC is the baseline; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.2",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Establish and enforce security configuration settings.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.2",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.4.2",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Checkov/Trivy enforce config in CI; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.3",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Track, review, approve, and audit changes.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.4.3",
        "status": "policy",
        "method": "POLICY",
        "summary": "Git history + PR reviews + branch protection; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.4",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Analyze security impact of changes prior to implementation.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.4.4",
        "status": "policy",
        "method": "POLICY",
        "summary": "PR review + IaC scanning gates; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.5",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Define and enforce access restrictions for changes.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.4.5",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Branch protection + required reviews; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.6",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Employ least functionality; disable nonessential services.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.4.6",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Minimal container image; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.7",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Restrict nonessential programs, ports, protocols, services.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.4.7",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Security-group chaining restricts ports; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.8",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Apply deny-by-exception (blocklist) / permit-by-exception.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.8",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.4.8",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Allowlisted ingress via SGs; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.4.9",
      "family": "CM",
      "family_name": "Configuration Management",
      "title": "Control and monitor user-installed software.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "CM.L2-3.4.9",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.4.9",
        "status": "na",
        "method": "N/A",
        "summary": "Managed container images; no user-installed software.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.1",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Identify system users and processes.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L1-3.5.1",
        "hipaa": "164.312(a)(2)(i)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.1",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Unique user accounts per tenant; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.2",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Authenticate users and processes before access.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L1-3.5.2",
        "hipaa": "164.312(d)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.2",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Session auth on every request; overlaps 3.1.1.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.3",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Use multifactor authentication for account access.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.3",
        "hipaa": "164.312(d)",
        "onc": "170.315(d)(13)",
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.5.3",
        "status": "met",
        "method": "EXAMINE",
        "summary": "TOTP multifactor authentication (RFC 6238 via pyotp) is implemented and enforced at login when tenant.mfa_required is set, applying to privileged and non-privileged accounts alike.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/routes/mfa.py:4",
            "detail": "pyotp TOTP setup/verify implements the second factor."
          },
          {
            "kind": "source-file",
            "ref": "backend/routes/auth.py:71",
            "detail": "Login enforces TOTP when tenant.mfa_required is enabled."
          }
        ],
        "objective_ids": [
          "3.5.3[b]",
          "3.5.3[e]"
        ],
        "collector": "access_control",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "3f070c86830d53df67302643edf23d6143dd603c3a20974a32c796a73c0e5477"
      }
    },
    {
      "id": "3.5.4",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Employ replay-resistant authentication mechanisms.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.4",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "TOTP + session cookies over TLS; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.5",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Prevent reuse of identifiers for a defined period.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.5",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "User IDs never reused; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.6",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Disable identifiers after a period of inactivity.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.5.6",
        "status": "policy",
        "method": "POLICY",
        "summary": "Inactive-account disablement; policy-driven.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.7",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Enforce minimum password complexity.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.7",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "12-char mixed-class policy in password_validator; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.8",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Prohibit password reuse for a number of generations.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.8",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.8",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Password history policy; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.9",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Allow temporary password use with immediate change.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.9",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.5.9",
        "status": "policy",
        "method": "POLICY",
        "summary": "Admin-reset flow forces change; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.10",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Store and transmit only cryptographically-protected passwords.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.10",
        "hipaa": "164.312(a)(2)(iv)",
        "onc": "170.315(d)(12)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.10",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Werkzeug scrypt hashing; overlaps 3.13.11.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.5.11",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Obscure feedback of authentication information.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "IA.L2-3.5.11",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.5.11",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Masked password fields; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.6.1",
      "family": "IR",
      "family_name": "Incident Response",
      "title": "Establish an operational incident-handling capability.",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "IR.L2-3.6.1",
        "hipaa": "164.308(a)(6)(i)",
        "onc": null,
        "part2": "2.16"
      },
      "status": "policy",
      "finding": {
        "control_id": "3.6.1",
        "status": "policy",
        "method": "POLICY",
        "summary": "IR plan + GuardDuty/CloudTrail; see docs/runbooks/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.6.2",
      "family": "IR",
      "family_name": "Incident Response",
      "title": "Track, document, and report incidents.",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "IR.L2-3.6.2",
        "hipaa": "164.308(a)(6)(ii)",
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.6.2",
        "status": "policy",
        "method": "POLICY",
        "summary": "Incident tracking + reporting; see docs/runbooks/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.6.3",
      "family": "IR",
      "family_name": "Incident Response",
      "title": "Test the organizational incident response capability.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "IR.L2-3.6.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.6.3",
        "status": "policy",
        "method": "POLICY",
        "summary": "Tabletop exercises; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.7.1",
      "family": "MA",
      "family_name": "Maintenance",
      "title": "Perform maintenance on organizational systems.",
      "sprs_weight": 3,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MA.L2-3.7.1",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.7.1",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "Underlying hardware maintenance performed by AWS.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.7.2",
      "family": "MA",
      "family_name": "Maintenance",
      "title": "Provide controls on tools, techniques, and personnel for maintenance.",
      "sprs_weight": 5,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MA.L2-3.7.2",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.7.2",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "Physical/hardware maintenance controlled by AWS.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.7.3",
      "family": "MA",
      "family_name": "Maintenance",
      "title": "Sanitize equipment removed for off-site maintenance.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MA.L2-3.7.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.7.3",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS media sanitization (NIST 800-88).",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.7.4",
      "family": "MA",
      "family_name": "Maintenance",
      "title": "Check media containing diagnostic programs for malicious code.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "MA.L2-3.7.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.7.4",
        "status": "na",
        "method": "N/A",
        "summary": "No diagnostic media in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.7.5",
      "family": "MA",
      "family_name": "Maintenance",
      "title": "Require MFA for nonlocal maintenance sessions.",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "MA.L2-3.7.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.7.5",
        "status": "policy",
        "method": "POLICY",
        "summary": "ECS exec via SSM with IAM; MFA on console; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.7.6",
      "family": "MA",
      "family_name": "Maintenance",
      "title": "Supervise maintenance activities of personnel without access.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MA.L2-3.7.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.7.6",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS supervises data-center maintenance personnel.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.1",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Protect system media containing CUI.",
      "sprs_weight": 3,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.1",
        "hipaa": "164.310(d)(1)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.8.1",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "Storage media secured by AWS; data encrypted with KMS.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.2",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Limit access to CUI on system media.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.2",
        "hipaa": "164.310(d)(1)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.8.2",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "S3/RDS access restricted via IAM/SG; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.3",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Sanitize or destroy media before disposal or reuse.",
      "sprs_weight": 5,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MP.L1-3.8.3",
        "hipaa": "164.310(d)(2)(i)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.8.3",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS media sanitization on decommission (NIST 800-88).",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.4",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Mark media with necessary CUI markings.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.8.4",
        "status": "na",
        "method": "N/A",
        "summary": "No physical media to mark.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.5",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Control access to media during transport.",
      "sprs_weight": 3,
      "type": "na",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.8.5",
        "status": "na",
        "method": "N/A",
        "summary": "No physical media transport.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.6",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Use cryptographic protection for CUI on media during transport.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.8.6",
        "status": "na",
        "method": "N/A",
        "summary": "No physical media transport; data encrypted at rest via KMS.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.7",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Control the use of removable media.",
      "sprs_weight": 3,
      "type": "na",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.8.7",
        "status": "na",
        "method": "N/A",
        "summary": "No removable media in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.8",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Prohibit use of portable storage with no identifiable owner.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.8",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.8.8",
        "status": "na",
        "method": "N/A",
        "summary": "No portable storage in scope.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.8.9",
      "family": "MP",
      "family_name": "Media Protection",
      "title": "Protect the confidentiality of backup CUI at storage locations.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "MP.L2-3.8.9",
        "hipaa": "164.308(a)(7)(ii)(A)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.8.9",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "RDS automated backups encrypted with KMS in AWS.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.9.1",
      "family": "PS",
      "family_name": "Personnel Security",
      "title": "Screen individuals prior to authorizing access to CUI.",
      "sprs_weight": 3,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "PS.L2-3.9.1",
        "hipaa": "164.308(a)(3)(ii)(B)",
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.9.1",
        "status": "policy",
        "method": "POLICY",
        "summary": "Background screening policy; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.9.2",
      "family": "PS",
      "family_name": "Personnel Security",
      "title": "Protect CUI during and after personnel actions (termination/transfer).",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "PS.L2-3.9.2",
        "hipaa": "164.308(a)(3)(ii)(C)",
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.9.2",
        "status": "policy",
        "method": "POLICY",
        "summary": "Deprovisioning on termination; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.10.1",
      "family": "PE",
      "family_name": "Physical Protection",
      "title": "Limit physical access to systems and equipment.",
      "sprs_weight": 5,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "PE.L1-3.10.1",
        "hipaa": "164.310(a)(1)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.10.1",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS data-center physical security (SOC 2 / FedRAMP).",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.10.2",
      "family": "PE",
      "family_name": "Physical Protection",
      "title": "Protect and monitor the physical facility and infrastructure.",
      "sprs_weight": 5,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "PE.L2-3.10.2",
        "hipaa": "164.310(a)(2)(ii)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.10.2",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS facility protection and monitoring.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.10.3",
      "family": "PE",
      "family_name": "Physical Protection",
      "title": "Escort visitors and monitor visitor activity.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "PE.L1-3.10.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.10.3",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS visitor controls at data centers.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.10.4",
      "family": "PE",
      "family_name": "Physical Protection",
      "title": "Maintain audit logs of physical access.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "PE.L1-3.10.4",
        "hipaa": "164.310(a)(2)(iii)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.10.4",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS physical access logging.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.10.5",
      "family": "PE",
      "family_name": "Physical Protection",
      "title": "Control and manage physical access devices.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "PE.L1-3.10.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.10.5",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS badge/key management.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.10.6",
      "family": "PE",
      "family_name": "Physical Protection",
      "title": "Enforce safeguarding measures for CUI at alternate work sites.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "PE.L2-3.10.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.10.6",
        "status": "policy",
        "method": "POLICY",
        "summary": "Remote-work security policy; see docs/policies/.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.11.1",
      "family": "RA",
      "family_name": "Risk Assessment",
      "title": "Periodically assess risk to operations and assets.",
      "sprs_weight": 3,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "RA.L2-3.11.1",
        "hipaa": "164.308(a)(1)(ii)(A)",
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.11.1",
        "status": "policy",
        "method": "POLICY",
        "summary": "HIPAA Risk Analysis; see docs/risk-analysis.md.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.11.2",
      "family": "RA",
      "family_name": "Risk Assessment",
      "title": "Scan for vulnerabilities periodically and when new ones arise.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "RA.L2-3.11.2",
        "hipaa": "164.308(a)(1)(ii)(A), 164.308(a)(8)",
        "onc": null,
        "part2": null
      },
      "status": "partial",
      "finding": {
        "control_id": "3.11.2",
        "status": "partial",
        "method": "EXAMINE",
        "summary": "Vulnerability scanning (pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps)) runs on every push/PR, but not on a fixed schedule, so newly disclosed CVEs in unchanged dependencies are not caught until the next commit.",
        "evidence": [
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "Scan frequency defined by triggers: push, pull_request."
          },
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "POA&M: add a scheduled (cron) scan to satisfy 3.11.2[d] for newly identified vulnerabilities."
          }
        ],
        "objective_ids": [
          "3.11.2[a]"
        ],
        "collector": "flaw_remediation",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "db60d2bac5b02da87f68f7ca18f0e6f8add4ba242e9928450a2b6cd09a85f07e"
      }
    },
    {
      "id": "3.11.3",
      "family": "RA",
      "family_name": "Risk Assessment",
      "title": "Remediate vulnerabilities in accordance with risk assessments.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "RA.L2-3.11.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.11.3",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "CI gates block HIGH/CRITICAL; overlaps 3.14.1.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.12.1",
      "family": "CA",
      "family_name": "Security Assessment",
      "title": "Periodically assess security controls for effectiveness.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "CA.L2-3.12.1",
        "hipaa": "164.308(a)(8)",
        "onc": null,
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.12.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "This engine assesses every cataloged control on each run and on a schedule.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "compliance/run.py",
            "detail": "run.py executes all collectors and scores the controls."
          }
        ],
        "objective_ids": [
          "3.12.1"
        ],
        "collector": "self_assessment",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "c076dee48c67788e34213e6536ab1f8f332f4ac535fbc8fa24c2bea8a231ea2d"
      }
    },
    {
      "id": "3.12.2",
      "family": "CA",
      "family_name": "Security Assessment",
      "title": "Develop and implement plans of action (POA&M).",
      "sprs_weight": 3,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "CA.L2-3.12.2",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.12.2",
        "status": "met",
        "method": "EXAMINE",
        "summary": "A Plan of Action & Milestones is auto-generated from the assessment results.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "compliance/generate_docs.py",
            "detail": "generate_docs.py renders POAM.md and POAM.csv from status.json."
          }
        ],
        "objective_ids": [
          "3.12.2"
        ],
        "collector": "self_assessment",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "fc90c8132923de8f926c4c00b6142281cf780fdc2455607dd764d185f706c5ec"
      }
    },
    {
      "id": "3.12.3",
      "family": "CA",
      "family_name": "Security Assessment",
      "title": "Monitor security controls on an ongoing basis.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "CA.L2-3.12.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.12.3",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Controls are monitored continuously by a scheduled GitHub Actions workflow with a drift gate.",
        "evidence": [
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/compliance.yml",
            "detail": "compliance.yml re-runs the assessment daily and commits refreshed evidence."
          }
        ],
        "objective_ids": [
          "3.12.3"
        ],
        "collector": "self_assessment",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "8ec5b8a657efb90e9cad2aae36509cdd8620ff65a3663787001ff255e09e5ad1"
      }
    },
    {
      "id": "3.12.4",
      "family": "CA",
      "family_name": "Security Assessment",
      "title": "Develop and maintain a System Security Plan (SSP).",
      "sprs_weight": 0,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "CA.L2-3.12.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.12.4",
        "status": "met",
        "method": "EXAMINE",
        "summary": "A System Security Plan is auto-generated from the control implementations.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "compliance/generate_docs.py",
            "detail": "generate_docs.py renders SSP.md from status.json."
          }
        ],
        "objective_ids": [
          "3.12.4"
        ],
        "collector": "self_assessment",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "0514e8cfdd941f70939fd2b845079c895070344e3defa8d09f37b8732f94ffb6"
      }
    },
    {
      "id": "3.13.1",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Monitor, control, and protect communications at boundaries.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L1-3.13.1",
        "hipaa": "164.312(e)(1)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.1",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "VPC tiers + SG chaining + WAF; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.2",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Employ architectural designs promoting effective security.",
      "sprs_weight": 5,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.2",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.13.2",
        "status": "policy",
        "method": "POLICY",
        "summary": "Documented secure architecture; see ARCHITECTURE.md.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.3",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Separate user functionality from system management.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.3",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Separate admin routes/permissions; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.4",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Prevent unauthorized information transfer via shared resources.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.4",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Per-tenant isolation + tenant_id scoping; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.5",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Implement subnetworks for publicly accessible components.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L1-3.13.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.5",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Public/private/isolated subnet tiers; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.6",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Deny network traffic by default; allow by exception.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.6",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Security groups deny-by-default; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.7",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Prevent split tunneling for remote devices.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.13.7",
        "status": "na",
        "method": "N/A",
        "summary": "No remote VPN/devices in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.8",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Use cryptography to protect CUI during transmission.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.8",
        "hipaa": "164.312(e)(1), 164.312(e)(2)(ii)",
        "onc": "170.315(d)(9)",
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.13.8",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Data in transit is encrypted end to end: TLS 1.2+ is enforced at CloudFront and the ALB, and RDS refuses non-TLS connections.",
        "evidence": [
          {
            "kind": "terraform",
            "ref": "infra/rds.tf:23",
            "detail": "RDS parameter rds.force_ssl=1 rejects any non-TLS database connection."
          },
          {
            "kind": "terraform",
            "ref": "infra/alb.tf:109",
            "detail": "ALB HTTPS listener uses a TLS 1.2/1.3 security policy."
          },
          {
            "kind": "terraform",
            "ref": "infra/cloudfront.tf:205",
            "detail": "CloudFront enforces a minimum TLS 1.2 viewer protocol version."
          },
          {
            "kind": "terraform",
            "ref": "infra/cloudfront.tf:149",
            "detail": "CloudFront redirects all viewer traffic to HTTPS."
          }
        ],
        "objective_ids": [
          "3.13.8[c]"
        ],
        "collector": "crypto_config",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "2136645358e39391e3ab8a11eee4924e3a79e97531158c11a090bdaecc8e9f83"
      }
    },
    {
      "id": "3.13.9",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Terminate network connections after inactivity.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.9",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.9",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Idle timeouts on sessions/keepalive; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.10",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Establish and manage cryptographic keys.",
      "sprs_weight": 1,
      "type": "inherited",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.10",
        "hipaa": "164.312(a)(2)(iv)",
        "onc": null,
        "part2": null
      },
      "status": "inherited",
      "finding": {
        "control_id": "3.13.10",
        "status": "inherited",
        "method": "INHERITED",
        "summary": "AWS KMS manages key lifecycle and rotation.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.11",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Employ FIPS-validated cryptography to protect CUI.",
      "sprs_weight": 3,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.11",
        "hipaa": "164.312(a)(2)(iv), 164.312(e)(2)(ii)",
        "onc": "170.315(d)(7), 170.315(d)(12)",
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.13.11",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Confidentiality is protected with FIPS 140-2 validated cryptography: AWS KMS customer-managed keys (rotated) encrypt RDS storage, Secrets Manager, logs, and S3; TLS in transit terminates on AWS's FIPS-capable endpoints.",
        "evidence": [
          {
            "kind": "terraform",
            "ref": "infra/kms.tf:19",
            "detail": "4 customer-managed AWS KMS key(s) defined. AWS KMS HSMs are FIPS 140-2 validated (NIST CMVP)."
          },
          {
            "kind": "terraform",
            "ref": "infra/kms.tf:21",
            "detail": "Automatic annual key rotation is enabled on the KMS keys."
          },
          {
            "kind": "terraform",
            "ref": "infra/rds.tf:85",
            "detail": "RDS storage is encrypted at rest using a customer-managed KMS key."
          }
        ],
        "objective_ids": [
          "3.13.11[a]"
        ],
        "collector": "crypto_config",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "9ad52e2681f2b5bce8d73db0981fdc48e0a3f8a8e5d1959fefa4013c6143b8d4"
      }
    },
    {
      "id": "3.13.12",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Prohibit remote activation of collaborative computing devices.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.12",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.13.12",
        "status": "na",
        "method": "N/A",
        "summary": "No cameras/microphones in scope.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.13",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Control and monitor use of mobile code.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.13",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.13",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "CSP/headers restrict client code; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.14",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Control and monitor use of Voice over IP.",
      "sprs_weight": 1,
      "type": "na",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.14",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "na",
      "finding": {
        "control_id": "3.13.14",
        "status": "na",
        "method": "N/A",
        "summary": "No VoIP in the SaaS boundary.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.15",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Protect authenticity of communications sessions.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.15",
        "hipaa": null,
        "onc": "170.315(d)(9)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.15",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "TLS + httpOnly SameSite session cookies; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.13.16",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Protect the confidentiality of CUI at rest.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SC.L2-3.13.16",
        "hipaa": "164.312(a)(2)(iv)",
        "onc": "170.315(d)(7)",
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.13.16",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "RDS/S3/Secrets encrypted with KMS; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.14.1",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Identify, report, and correct system flaws in a timely manner.",
      "sprs_weight": 5,
      "type": "automated",
      "mappings": {
        "cmmc_l2": "SI.L1-3.14.1",
        "hipaa": "164.308(a)(5)(ii)(B)",
        "onc": null,
        "part2": null
      },
      "status": "met",
      "finding": {
        "control_id": "3.14.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "System flaws are identified by Bandit (SAST), pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps); findings gate the pipeline (exit-code 1), forcing correction before code merges.",
        "evidence": [
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "5 scanners configured: Bandit (SAST), pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps)."
          },
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "A HIGH/CRITICAL finding fails the build (exit-code 1), blocking merge until the flaw is corrected."
          }
        ],
        "objective_ids": [
          "3.14.1[b]",
          "3.14.1[c]"
        ],
        "collector": "flaw_remediation",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": "3f153b6b1e8f5801eacdc225dba7cf952d9ba9eca384f2fa489fde367154ae62"
      }
    },
    {
      "id": "3.14.2",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Provide protection from malicious code.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SI.L1-3.14.2",
        "hipaa": "164.308(a)(5)(ii)(B)",
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.14.2",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Trivy image/dep scanning in CI; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.14.3",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Monitor system security alerts and advisories; act on them.",
      "sprs_weight": 1,
      "type": "policy",
      "mappings": {
        "cmmc_l2": "SI.L2-3.14.3",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "policy",
      "finding": {
        "control_id": "3.14.3",
        "status": "policy",
        "method": "POLICY",
        "summary": "pip-audit/Trivy advisories + GuardDuty; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.14.4",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Update malicious code protection mechanisms.",
      "sprs_weight": 1,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SI.L1-3.14.4",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.14.4",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Trivy DB updated each CI run; collector pending.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.14.5",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Perform periodic and real-time scans of the system.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SI.L1-3.14.5",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.14.5",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "CI scans on every change; overlaps 3.11.2.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.14.6",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Monitor systems to detect attacks and indicators.",
      "sprs_weight": 5,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SI.L2-3.14.6",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.14.6",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "GuardDuty + VPC Flow Logs + CloudTrail; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    },
    {
      "id": "3.14.7",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Identify unauthorized use of organizational systems.",
      "sprs_weight": 3,
      "type": "attested",
      "mappings": {
        "cmmc_l2": "SI.L2-3.14.7",
        "hipaa": null,
        "onc": null,
        "part2": null
      },
      "status": "attested",
      "finding": {
        "control_id": "3.14.7",
        "status": "attested",
        "method": "ATTESTED",
        "summary": "Audit log + GuardDuty anomaly detection; attested.",
        "evidence": [],
        "objective_ids": [],
        "collector": "catalog",
        "collected_at": "2026-07-01T08:47:48+00:00",
        "evidence_hash": ""
      }
    }
  ],
  "repo": {
    "url": "https://github.com/adrianbcaballero/AegleroEMR",
    "branch": "main"
  }
};
