// AUTO-GENERATED by generate_docs.py -- do not edit.
window.COMPLIANCE_STATUS = {
  "generated_at": "2026-07-01T04:52:16+00:00",
  "framework": "NIST SP 800-171 Rev 2",
  "scoring_model": "DoD Assessment Methodology (SPRS), base score 110",
  "summary": {
    "sprs_score": 105,
    "sprs_base": 110,
    "points_deducted": 5,
    "sprs_basis": "partial catalog (10 of 110 controls seeded); score is conservative (unassessed = not implemented)",
    "automated_coverage_pct": 100.0,
    "controls_total": 10,
    "controls_applicable": 10,
    "controls_with_evidence": 10,
    "status_counts": {
      "met": 9,
      "partial": 1
    },
    "deductions": [
      {
        "control_id": "3.11.2",
        "status": "partial",
        "points": 5,
        "reason": "Vulnerability scanning (pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps)) runs on every push/PR, but not on a fixed schedule, so newly disclosed CVEs in unchanged dependencies are not caught until the next commit."
      }
    ]
  },
  "controls": [
    {
      "id": "3.3.1",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.3.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Audit records are generated by log_access() and persisted to the AuditLog table (retained in Postgres).",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:29",
            "detail": "log_access() creates and stores an AuditLog row per event."
          }
        ],
        "objective_ids": [
          "3.3.1[e]",
          "3.3.1[f]"
        ],
        "collector": "audit_chain",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "f44ccc756422e990d90db7754db655b5445a7229fbabc0130fe7245abfff8311"
      }
    },
    {
      "id": "3.3.2",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Ensure that the actions of individual system users can be uniquely traced to those users, so they can be held accountable for their actions.",
      "sprs_weight": 3,
      "status": "met",
      "finding": {
        "control_id": "3.3.2",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Every audit record carries user_id, uniquely tracing actions to the acting user.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:9",
            "detail": "user_id is part of the audit record content and hash input."
          }
        ],
        "objective_ids": [
          "3.3.2[a]",
          "3.3.2[b]"
        ],
        "collector": "audit_chain",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "3041c5b18177bd668cd72539c862fcb13209630f70b6805d298e96d5da3c832f"
      }
    },
    {
      "id": "3.3.8",
      "family": "AU",
      "family_name": "Audit and Accountability",
      "title": "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.3.8",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Audit log is tamper-evident: a per-tenant SHA-256 hash chain makes any modification or deletion of a past record mathematically detectable via /api/audit/verify.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:9",
            "detail": "_compute_hash() = SHA-256(content || prev_hash) builds the chain."
          },
          {
            "kind": "source-file",
            "ref": "backend/services/audit_logger.py:9",
            "detail": "Each entry references the previous entry's hash (per-tenant chain)."
          },
          {
            "kind": "source-file",
            "ref": "backend/routes/audit.py:246",
            "detail": "GET /api/audit/verify walks the chain and reports tampering."
          }
        ],
        "objective_ids": [
          "3.3.8[b]",
          "3.3.8[c]"
        ],
        "collector": "audit_chain",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "7e1ab282570bf134086265d971dbaf722f5bb6d65617ca09be6f92bee8c7b473"
      }
    },
    {
      "id": "3.1.1",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.1.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "All protected routes require authentication via the require_auth decorator; unauthenticated requests are rejected.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/auth_middleware.py:47",
            "detail": "require_auth() authenticates the session before the handler runs."
          }
        ],
        "objective_ids": [
          "3.1.1[e]"
        ],
        "collector": "access_control",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "c052f0e419b984d466166797991efc9b9c7009f692386f9ad654eb59b9078dea"
      }
    },
    {
      "id": "3.1.2",
      "family": "AC",
      "family_name": "Access Control",
      "title": "Limit system access to the types of transactions and functions that authorized users are permitted to execute.",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.1.2",
        "status": "met",
        "method": "EXAMINE",
        "summary": "RBAC restricts each route to a required permission (has_permission), and patient visibility is further limited to a user's care teams (_apply_rbac).",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/auth_middleware.py:71",
            "detail": "require_auth(permission=...) enforces per-route permission."
          },
          {
            "kind": "source-file",
            "ref": "backend/routes/patients.py:148",
            "detail": "_apply_rbac() limits patient rows to the caller's care teams."
          }
        ],
        "objective_ids": [
          "3.1.2[b]"
        ],
        "collector": "access_control",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "e03f1d4c6bf4772c036383d4e24596ed4de2691f8226ba1ca4f900b1a8c0bb2a"
      }
    },
    {
      "id": "3.5.3",
      "family": "IA",
      "family_name": "Identification and Authentication",
      "title": "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.5.3",
        "status": "met",
        "method": "EXAMINE",
        "summary": "TOTP multifactor authentication (RFC 6238 via pyotp) is implemented and enforced at login when tenant.mfa_required is set, applying to privileged and non-privileged accounts alike.",
        "evidence": [
          {
            "kind": "source-file",
            "ref": "backend/routes/mfa.py:4",
            "detail": "pyotp TOTP setup/verify implements the second factor."
          },
          {
            "kind": "source-file",
            "ref": "backend/routes/auth.py:71",
            "detail": "Login enforces TOTP when tenant.mfa_required is enabled."
          }
        ],
        "objective_ids": [
          "3.5.3[b]",
          "3.5.3[e]"
        ],
        "collector": "access_control",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "3f070c86830d53df67302643edf23d6143dd603c3a20974a32c796a73c0e5477"
      }
    },
    {
      "id": "3.13.8",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.13.8",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Data in transit is encrypted end to end: TLS 1.2+ is enforced at CloudFront and the ALB, and RDS refuses non-TLS connections.",
        "evidence": [
          {
            "kind": "terraform",
            "ref": "infra/rds.tf:23",
            "detail": "RDS parameter rds.force_ssl=1 rejects any non-TLS database connection."
          },
          {
            "kind": "terraform",
            "ref": "infra/alb.tf:109",
            "detail": "ALB HTTPS listener uses a TLS 1.2/1.3 security policy."
          },
          {
            "kind": "terraform",
            "ref": "infra/cloudfront.tf:205",
            "detail": "CloudFront enforces a minimum TLS 1.2 viewer protocol version."
          },
          {
            "kind": "terraform",
            "ref": "infra/cloudfront.tf:149",
            "detail": "CloudFront redirects all viewer traffic to HTTPS."
          }
        ],
        "objective_ids": [
          "3.13.8[c]"
        ],
        "collector": "crypto_config",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "2136645358e39391e3ab8a11eee4924e3a79e97531158c11a090bdaecc8e9f83"
      }
    },
    {
      "id": "3.13.11",
      "family": "SC",
      "family_name": "System and Communications Protection",
      "title": "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.",
      "sprs_weight": 3,
      "status": "met",
      "finding": {
        "control_id": "3.13.11",
        "status": "met",
        "method": "EXAMINE",
        "summary": "Confidentiality is protected with FIPS 140-2 validated cryptography: AWS KMS customer-managed keys (rotated) encrypt RDS storage, Secrets Manager, logs, and S3; TLS in transit terminates on AWS's FIPS-capable endpoints.",
        "evidence": [
          {
            "kind": "terraform",
            "ref": "infra/kms.tf:19",
            "detail": "4 customer-managed AWS KMS key(s) defined. AWS KMS HSMs are FIPS 140-2 validated (NIST CMVP)."
          },
          {
            "kind": "terraform",
            "ref": "infra/kms.tf:21",
            "detail": "Automatic annual key rotation is enabled on the KMS keys."
          },
          {
            "kind": "terraform",
            "ref": "infra/rds.tf:85",
            "detail": "RDS storage is encrypted at rest using a customer-managed KMS key."
          }
        ],
        "objective_ids": [
          "3.13.11[a]"
        ],
        "collector": "crypto_config",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "9ad52e2681f2b5bce8d73db0981fdc48e0a3f8a8e5d1959fefa4013c6143b8d4"
      }
    },
    {
      "id": "3.14.1",
      "family": "SI",
      "family_name": "System and Information Integrity",
      "title": "Identify, report, and correct system flaws in a timely manner.",
      "sprs_weight": 5,
      "status": "met",
      "finding": {
        "control_id": "3.14.1",
        "status": "met",
        "method": "EXAMINE",
        "summary": "System flaws are identified by Bandit (SAST), pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps); findings gate the pipeline (exit-code 1), forcing correction before code merges.",
        "evidence": [
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "5 scanners configured: Bandit (SAST), pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps)."
          },
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "A HIGH/CRITICAL finding fails the build (exit-code 1), blocking merge until the flaw is corrected."
          }
        ],
        "objective_ids": [
          "3.14.1[b]",
          "3.14.1[c]"
        ],
        "collector": "flaw_remediation",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "3f153b6b1e8f5801eacdc225dba7cf952d9ba9eca384f2fa489fde367154ae62"
      }
    },
    {
      "id": "3.11.2",
      "family": "RA",
      "family_name": "Risk Assessment",
      "title": "Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.",
      "sprs_weight": 5,
      "status": "partial",
      "finding": {
        "control_id": "3.11.2",
        "status": "partial",
        "method": "EXAMINE",
        "summary": "Vulnerability scanning (pip-audit (Python deps), Trivy (containers/IaC/deps), Checkov (IaC compliance), pnpm audit (JS deps)) runs on every push/PR, but not on a fixed schedule, so newly disclosed CVEs in unchanged dependencies are not caught until the next commit.",
        "evidence": [
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "Scan frequency defined by triggers: push, pull_request."
          },
          {
            "kind": "ci-pipeline",
            "ref": ".github/workflows/ci.yml",
            "detail": "POA&M: add a scheduled (cron) scan to satisfy 3.11.2[d] for newly identified vulnerabilities."
          }
        ],
        "objective_ids": [
          "3.11.2[a]"
        ],
        "collector": "flaw_remediation",
        "collected_at": "2026-07-01T04:52:16+00:00",
        "evidence_hash": "db60d2bac5b02da87f68f7ca18f0e6f8add4ba242e9928450a2b6cd09a85f07e"
      }
    }
  ],
  "repo": {
    "url": "https://github.com/adrianbcaballero/AegleroEMR",
    "branch": "main"
  }
};
