"""
Word (.docx) export of the System Security Plan.

Renders the same NIST SP 800-18 structured SSP that generate_docs produces as
Markdown, as a Word document, since an SSP is conventionally delivered as .docx.

Requires python-docx (see requirements.txt). This is OPTIONAL: if the package is
not installed, build() returns None and the caller continues without the .docx,
so the core engine keeps working with only the standard library.
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT_DIR = HERE / "output"
OUT_DOCX = OUTPUT_DIR / "SSP.docx"


def _bullet(doc, key: str, value) -> None:
    p = doc.add_paragraph(style="List Bullet")
    p.add_run(f"{key}: ").bold = True
    p.add_run(str(value))


def _note(doc, text: str) -> None:
    run = doc.add_paragraph().add_run(text)
    run.italic = True


def build(report: dict, profile: dict) -> Path | None:
    """Write output/SSP.docx and return its path, or None if python-docx is absent."""
    try:
        from docx import Document
    except ImportError:
        return None

    # Pulled at runtime (not module load) to avoid an import cycle with generate_docs.
    import generate_docs as gd

    status_label = gd.STATUS_LABEL
    ssp_statuses = gd.SSP_STATUSES
    responsibility = gd._responsibility
    approved = gd._load_approved()

    s = report["summary"]
    doc = Document()

    doc.add_heading(f"System Security Plan (SSP): {profile['system_name']}", level=0)
    _note(doc, f"Auto-generated by the Aeglero compliance engine on {report['generated_at']}. "
               "Do not hand-edit; regenerate from status.json.")
    _note(doc, "Section structure follows NIST SP 800-18 (Guide for Developing Security "
               "Plans); control implementation follows NIST SP 800-171 Rev 2.")
    _note(doc, profile.get("assessment_scope_note", ""))

    # ---- 1. System identification -------------------------------------------
    doc.add_heading("1. System identification", level=1)
    _bullet(doc, "System name", f"{profile['system_name']} ({profile.get('system_short_name', '')})")
    _bullet(doc, "System categorization (FIPS 199)", profile.get("categorization", "Not categorized"))
    _bullet(doc, "System type", profile.get("system_type", "-"))
    _bullet(doc, "Operational status", profile.get("operational_status", "-"))
    _bullet(doc, "System owner", profile.get("owner", "-"))
    _bullet(doc, "Authorizing official", profile.get("authorizing_official", "-"))
    _bullet(doc, "Assignment of security responsibility", profile.get("security_contact", "-"))
    _bullet(doc, "Version", profile.get("version", "-"))
    _bullet(doc, "Plan date", report["generated_at"])

    # ---- 2. System description and purpose ----------------------------------
    doc.add_heading("2. System description and purpose", level=1)
    doc.add_paragraph(profile["description"])
    _bullet(doc, "Information types processed", ", ".join(profile.get("data_types", [])))
    _bullet(doc, "Hosting", profile.get("hosting", "-"))

    # ---- 3. System environment and authorization boundary -------------------
    doc.add_heading("3. System environment and authorization boundary", level=1)
    doc.add_paragraph(profile["authorization_boundary"])

    # ---- 4. Applicable laws, regulations, and guidance ----------------------
    doc.add_heading("4. Applicable laws, regulations, and guidance", level=1)
    doc.add_paragraph().add_run("Binding laws and regulations.").bold = True
    for law in profile.get("applicable_laws", []) or ["Not specified."]:
        doc.add_paragraph(law, style="List Bullet")
    guidance = profile.get("guidance", [])
    if guidance:
        doc.add_paragraph().add_run("Referenced guidance.").bold = True
        for g in guidance:
            doc.add_paragraph(g, style="List Bullet")
    note = profile.get("assessment_framework_note")
    if note:
        p = doc.add_paragraph()
        p.add_run("Assessment framework. ").bold = True
        p.add_run(note)

    # ---- 5. Control implementation summary ----------------------------------
    doc.add_heading("5. Control implementation summary", level=1)
    _bullet(doc, "Framework", report["framework"])
    _bullet(doc, "SPRS score",
            f"{s['sprs_score']} / {s['sprs_base']} (-{s['points_deducted']}) - {s['sprs_basis']}")
    _bullet(doc, "Automated evidence coverage",
            f"{s['automated_coverage_pct']}% ({s['controls_with_evidence']} of "
            f"{s['controls_applicable']} applicable controls)")
    _bullet(doc, "Status breakdown", s["status_counts"])

    # ---- 6. Control implementation ------------------------------------------
    doc.add_heading("6. Control implementation", level=1)
    implemented = [c for c in report["controls"] if c["status"] in ssp_statuses]
    if not implemented:
        doc.add_paragraph("No implemented controls to report.")
    for c in implemented:
        f = c.get("finding") or {}
        doc.add_heading(f"{c['id']}: {c['title']}", level=2)
        _bullet(doc, "Family", f"{c['family']} ({c.get('family_name', '')})")
        _bullet(doc, "Implementation status", status_label.get(c["status"], c["status"]))
        _bullet(doc, "Responsibility", responsibility(c["status"]))
        _bullet(doc, "SPRS weight", c["sprs_weight"])
        if f:
            _bullet(doc, "Assessment method", f.get("method", "EXAMINE"))
            _bullet(doc, "Objectives addressed", ", ".join(f.get("objective_ids", [])) or "-")
            stmt = doc.add_paragraph()
            stmt.add_run("Implementation statement. ").bold = True
            appr = approved.get(c["id"])
            if appr:
                stmt.add_run(f"(drafted with AI assistance, reviewed and approved "
                             f"{appr.get('approved_at', '')}) {appr['statement']}")
            else:
                stmt.add_run(f.get("summary", ""))
            ev = f.get("evidence", [])
            if ev:
                doc.add_paragraph().add_run("Evidence.").bold = True
                for e in ev:
                    b = doc.add_paragraph(style="List Bullet")
                    b.add_run(f"{e.get('ref', '')}: ").bold = True
                    b.add_run(e.get("detail", ""))
            _note(doc, f"Provenance: collected by {f.get('collector', '')} at "
                       f"{f.get('collected_at', '')}; evidence SHA-256 "
                       f"{f.get('evidence_hash', '')[:16]}")

    # ---- 7. Plan completion --------------------------------------------------
    doc.add_heading("7. Plan completion", level=1)
    _bullet(doc, "Plan completion date", report["generated_at"])
    _bullet(doc, "Plan approval", profile.get("authorizing_official", "-"))

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    doc.save(OUT_DOCX)
    return OUT_DOCX
