"""
audit_chain collector - EXAMINE method.

Proves that Aeglero implements a tamper-evident audit log by examining the source
of the audit subsystem. This is legitimate assessment evidence under NIST 800-171A
(the "Examine" method: inspect the mechanism), and it needs no running server or
cloud credentials, so it is the Phase-1 starter collector.

Maps to:
  3.3.1 - audit logs are created and retained  (log_access writes AuditLog rows)
  3.3.2 - actions are uniquely traceable to users  (each entry records user_id)
  3.3.8 - audit information is protected from modification/deletion
          (per-tenant SHA-256 hash chain: entry_hash = SHA-256(content || prev_hash))
"""

from __future__ import annotations

from pathlib import Path

from .base import (
    Collector, CollectorContext, Finding, Evidence,
    STATUS_MET, STATUS_NOT_MET, STATUS_ERROR, METHOD_EXAMINE,
)

LOGGER_SRC = "backend/services/audit_logger.py"
ROUTES_SRC = "backend/routes/audit.py"


class AuditChainCollector(Collector):
    name = "audit_chain"
    provides = ["3.3.1", "3.3.2", "3.3.8"]
    method = METHOD_EXAMINE

    def collect(self, ctx: CollectorContext) -> list[Finding]:
        logger_path = ctx.repo_root / LOGGER_SRC
        routes_path = ctx.repo_root / ROUTES_SRC

        # If we can't even find the source, report ERROR, not a fake pass.
        if not logger_path.exists():
            return [
                self._error(cid, f"source not found: {LOGGER_SRC}")
                for cid in self.provides
            ]

        # Look for the concrete implementation markers.
        hash_impl = self.grep(logger_path, "hashlib.sha256")
        chain_impl = self.grep(logger_path, "prev_hash")
        compute_fn = self.grep(logger_path, "def _compute_hash")
        writes_log = self.grep(logger_path, "def log_access")
        records_user = self.grep(logger_path, "user_id")
        verify_ep = self.grep(routes_path, "/verify") if routes_path.exists() else []

        findings: list[Finding] = []

        # --- 3.3.1: logs are created and retained ---------------------------
        if writes_log:
            findings.append(Finding(
                control_id="3.3.1",
                status=STATUS_MET,
                method=METHOD_EXAMINE,
                summary="Audit records are generated by log_access() and persisted "
                        "to the AuditLog table (retained in Postgres).",
                objective_ids=["3.3.1[e]", "3.3.1[f]"],
                evidence=[
                    Evidence("source-file", f"{LOGGER_SRC}:{writes_log[0][0]}",
                             "log_access() creates and stores an AuditLog row per event."),
                ],
            ))
        else:
            findings.append(self._not_met("3.3.1", "No log_access() writer found."))

        # --- 3.3.2: actions traceable to users -----------------------------
        if records_user:
            findings.append(Finding(
                control_id="3.3.2",
                status=STATUS_MET,
                method=METHOD_EXAMINE,
                summary="Every audit record carries user_id, uniquely tracing actions "
                        "to the acting user.",
                objective_ids=["3.3.2[a]", "3.3.2[b]"],
                evidence=[
                    Evidence("source-file", f"{LOGGER_SRC}:{records_user[0][0]}",
                             "user_id is part of the audit record content and hash input."),
                ],
            ))
        else:
            findings.append(self._not_met("3.3.2", "Audit records do not record user_id."))

        # --- 3.3.8: audit info protected from modification/deletion --------
        if hash_impl and chain_impl and compute_fn:
            ev = [
                Evidence("source-file", f"{LOGGER_SRC}:{compute_fn[0][0]}",
                         "_compute_hash() = SHA-256(content || prev_hash) builds the chain."),
                Evidence("source-file", f"{LOGGER_SRC}:{chain_impl[0][0]}",
                         "Each entry references the previous entry's hash (per-tenant chain)."),
            ]
            if verify_ep:
                ev.append(Evidence(
                    "source-file", f"{ROUTES_SRC}:{verify_ep[0][0]}",
                    "GET /api/audit/verify walks the chain and reports tampering."))
            findings.append(Finding(
                control_id="3.3.8",
                status=STATUS_MET,
                method=METHOD_EXAMINE,
                summary="Audit log is tamper-evident: a per-tenant SHA-256 hash chain "
                        "makes any modification or deletion of a past record "
                        "mathematically detectable via /api/audit/verify.",
                objective_ids=["3.3.8[b]", "3.3.8[c]"],
                evidence=ev,
            ))
        else:
            findings.append(self._not_met(
                "3.3.8", "No hash-chain tamper-evidence found in the audit logger."))

        return findings

    # -- helpers ---------------------------------------------------------------

    def _not_met(self, cid: str, why: str) -> Finding:
        return Finding(control_id=cid, status=STATUS_NOT_MET,
                       method=METHOD_EXAMINE, summary=why)

    def _error(self, cid: str, why: str) -> Finding:
        return Finding(control_id=cid, status=STATUS_ERROR,
                       method=METHOD_EXAMINE, summary=why)
